---
name: Orchestrator

on:
  push:
    branches:
      - main

jobs:
  call-testing-pipeline:
    name: Testing
    uses: ./.github/workflows/test.yml
  call-linting-pipeline:
    name: Linting
    uses: ./.github/workflows/lint.yml
  call-build-pipeline:
    name: Build
    uses: ./.github/workflows/build.yml
  call-release-pipeline:
    name: Release
    needs:
      - call-testing-pipeline
      - call-linting-pipeline
      - call-build-pipeline
    uses: ./.github/workflows/release.yml
    secrets: inherit
